export const HERO_CODE_LINES: string[] = [
  "// {Code} · Desk — portfolio.config.ts",
  "import { createSite } from './lib/core';",
  "",
  "export const site = createSite({",
  "  name: '{Code} · Desk',",
  "  role: 'Frontend Developer & Designer',",
  "  stack: ['TypeScript', 'React', 'Next.js', 'GSAP'],",
  "});",
  "",
  "type Section = {",
  "  id: string;",
  "  title: string;",
  "  theme: 'light' | 'dark';",
  "};",
  "",
  "const sections: Section[] = [",
  "  { id: 'about', title: 'About', theme: 'light' },",
  "  { id: 'work', title: 'Work', theme: 'light' },",
  "  { id: 'service', title: 'Service', theme: 'dark' },",
  "  { id: 'contact', title: 'Contact', theme: 'dark' },",
  "];",
  "",
  "export function renderSections() {",
  "  return sections.map((section) => {",
  "    const node = mount(section.id);",
  "    node.dataset.theme = section.theme;",
  "    return node;",
  "  });",
  "}",
  "",
  "async function build() {",
  "  console.log('polishing pixels...');",
  "  await Promise.all([",
  "    optimizeImages(),",
  "    inlineCriticalCss(),",
  "    prefetchFonts(['Pretendard', 'Cormorant Garamond']),",
  "  ]);",
  "  return 'ready';",
  "}",
  "",
  "export default build;",
];
